### ISSUE TITLE
Bypass Email Verification

### ISSUE THREAD

**Issue by littlebroto1** [uahcyber/cyberbot#3]
A couple of weeks ago, I began exploring ways to bypass the `uah.edu` domain name requirement for the `!verify` command.

While collecting information, I noticed that the verification system uses a default python library, `smtplib`. Looking into the code of the [`sendmail`](https://github.com/python/cpython/blob/3.10/Lib/smtplib.py#L808-L910) method, I noticed a couple of security vulnerabilities involving the email parameter. The most obvious one was that it never checked the input for a `<` or `>` character.

The [`sendmail`](https://github.com/python/cpython/blob/e7de54321952ebb58cc414f2160c9ad4f6510af2/Lib/smtplib.py#L891-L897) method formats using [`rcpt`](https://github.com/python/cpython/blob/e7de54321952ebb58cc414f2160c9ad4f6510af2/Lib/smtplib.py#L548-L554), which in turn uses [`quoteaddr`](https://github.com/python/cpython/blob/e7de54321952ebb58cc414f2160c9ad4f6510af2/Lib/smtplib.py#L146-L157).

[`quoteaddr`](https://github.com/python/cpython/blob/e7de54321952ebb58cc414f2160c9ad4f6510af2/Lib/smtplib.py#L146-L157) surrounds the email with angled brackets `<` `>` if it is a valid email, but just directly takes the user input if it starts with `<`. This allows us to bypass the check using `<malicious@attacker.com>uah.edu`.

Also, with further examination, if found that attacks like `malicious@attacker.com:uah.edu` also worked. This is because the email parser sees addresses separated with `:` as a list. But in the code, it only sends mail to the first address in the list.

**Comment by dayt0n** [comment]
A fix for this vulnerability has been addressed in cb02b69704eb1d2a7609d452dbc26ae06f906404. 

Thank you for the report.
